#:schema node_modules/wrangler/config-schema.json
name = "sublink-work"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "c0d1a980667a42fe8929f9c0e288dcbb" }
]

[assets]
directory = "./public"
